### ISSUE TITLE
The project template you provider not compile

### ISSUE THREAD

**Issue by scascalespAV** [Umplify/xunit-dependency-injection#122]
The project template you provider not compile

https://github.com/Umplify/xunit-dependency-injection/tree/main/examples/Xunit.Microsoft.DependencyInjection.ExampleTests

Thanks

**Comment by scascalespAV** [comment]
Needs to donw all source

**Comment by Arash-Sabet** [comment]
@scascalespAV Thanks for reporting this issue. I will look into it.

**Comment by Arash-Sabet** [comment]
@scascalespAV My project template compiles and runs well by dotnet SDK version 6.0.401 per the following screenshot.

<img width="1949" alt="image" src="https://user-images.githubusercontent.com/26050123/193408389-4e22a770-ecb0-4a95-ba0b-07138c727c3a.png">

Could you please share the following information?

* The version of your SDK
* A screenshot of your console's output after running `dotnet test` command in `examples/Xunit.Microsoft.DependencyInjection.ExampleTests` folder?

**Comment by Arash-Sabet** [comment]
> Needs to donw all source

The primary purpose of the example tests project in the solution was to debug the main project's code. Therefore, a direct reference to the main library project is necessary. Should you wish to use the example project, please remove this reference `<ProjectReference Include="..\..\src\Xunit.Microsoft.DependencyInjection.csproj" />` in the test project and add the [NuGet package available here](https://www.nuget.org/packages/Xunit.Microsoft.DependencyInjection/).
