### ISSUE TITLE
Add support to add configuration from UserSecrets

### ISSUE THREAD

**Issue by Summpot** [Umplify/xunit-dependency-injection#127]
**Is your feature request related to a problem? Please describe.**
There is no way to read the configuration from the UserSecret, I can only write the secret directly in the appsettings in plain text.

**Describe the solution you'd like**
[Adding a configuration from UserSecrets is very simple.](https://learn.microsoft.com/en-us/dotnet/api/microsoft.extensions.configuration.usersecretsconfigurationextensions.addusersecrets?view=dotnet-plat-ext-7.0#microsoft-extensions-configuration-usersecretsconfigurationextensions-addusersecrets(microsoft-extensions-configuration-iconfigurationbuilder-system-reflection-assembly))
The only problem that needs to be solved is that you need to expose the ConfigurationBuilder in TestFixture, rather than adding the Configuration by filename, I don't know if the test project has restrictions on this aspect of the implementation, but exposing the ConfigurationBuilder is clearly a better choice.

**Comment by Arash-Sabet** [comment]
@Summpot I will look into this issue. Alternatively, you can feel free to fork this repo, implement your suggested approach and create a PR for my review.

**Comment by Arash-Sabet** [comment]
@Summpot The `ConfigurationBuilder`'s instance is already exposed per [this line](https://github.com/Umplify/xunit-dependency-injection/blob/3cdb596d60b3cc13a42384aa5329e011bd6f1ef7/src/Abstracts/TestBedFixture.cs#L19). It has to serve the purpose you're looking for. Therefore, I am closing this issue as no further actions is required in this context.
