### ISSUE TITLE
Adopt .NET 6.0

### ISSUE THREAD

**Issue by Arash-Sabet** [Umplify/xunit-dependency-injection#72]
This has to start with using Microsoft's .NET 6.0's RC NuGet packages.

**Comment by adipuscasu** [comment]
@Arash-Sabet Is it possible to lower the required .NET version to .NET Core 3.1?
I would like to update to the latest version of this nuget but I'm not able because the project where I need this is only allowed to use LTS .NET versions.

**Comment by Arash-Sabet** [comment]
@adipuscasu I'm afraid not. The project has recently been upgraded to .NET 6.0 rc2.x and I guess downgrading it again won't be helpful in the long run. Microsoft is releasing VS 2022 and .NET 6.0 on Monday, Nov 8th and that will result in rolling out a new version of this library.
