### ISSUE TITLE
Add support for loading environment depending appsetings.json file

### ISSUE THREAD

**Issue by adipuscasu** [Umplify/xunit-dependency-injection#75]
At the moment, we are able to specify the name of the JSON configuration file, which is typically ```appsettings.json```.
We should be able to load configuration settings from other files like ```appsettings.dev.json```
We usually do this by chaining ```AddJsonFile(...```
If you could expose the builder object, then we could implement this directly in our project.

**Comment by Arash-Sabet** [comment]
@adipuscasu Just wondering, doesn't [this approach](https://github.com/Umplify/xunit-dependency-injection/blob/1c31c01ea0a9402a8fcf8343bf221aa2b02cc41f/examples/Xunit.Microsoft.DependencyInjection.ExampleTests/Fixtures/TestFixture.cs#L19-L20) work for you? When you derive your fixture class from `TestBedFixture` you will easily be able to supply any appsettings.X.json file names.

**Comment by adipuscasu** [comment]
That approach allows loading configuration data from a single file, but if I define the majority of the settings in the ```appsettings.json``` file and then define the environment specific settings in the ```environment.dev.json``` file, I can't load both of these files.

**Comment by Arash-Sabet** [comment]
@adipuscasu Makes sense. 
Just to be precise, do you want `ConfigurationBuilder` object to be exposed? I will schedule this development or you can alternatively fork this repo, develop this request and create a PR for my review and approval.

**Comment by adipuscasu** [comment]
I think that it would be simpler to add a new overridable method named ```GetConfigurationFiles``` and that would return the string array of "appsettings.XYZ.json". It could be implemented to implicitly return an array with one item containing the file gotten from the ```GetConfigurationFile``` method. That way it would not add breaking changes for the existing users.
But that is only a suggestion.
I'll try to find some time to fork the repo and make a PR, unless you prefer to implement something to enable this functionality, until then.

**Comment by Arash-Sabet** [comment]
@adipuscasu I think I can make that change quickly.

**Comment by Arash-Sabet** [comment]
@adipuscasu The change was released to NuGet.org. Please upgrade your NuGet package to obtain version 6.1.2. Thanks for this constructive suggestion.
